<div id="admin-wheel-controls" class="hidden flex-col gap-4 mt-8 w-full max-w-[720px] bg-white rounded-2xl p-6 shadow-md border border-gray-200 z-10 relative">
  <h2 class="text-xl font-bold text-brand-primary mb-2">لوحة تحكم العجلة (للمشرفين)</h2>
  <div id="general-controls">
    <!-- Generated by newLifeWheel.js -->
    <label>
      زاوية الدوران
      <div class="row">
        <input type="range" id="rotationSlider" min="0" max="359" step="1" value="0">
        <span id="rotationVal" style="width:44px;text-align:center;font-weight:700;color:var(--text-strong);">0&deg;</span>
      </div>
    </label>
    <label>
      اتجاه الدوران
      <select id="spinDirectionSelect">
        <option value="cw">يمين (مع عقارب الساعة)</option>
        <option value="ccw">شمال (عكس عقارب الساعة)</option>
      </select>
    </label>
    <label class="checkbox-row">
      <input type="checkbox" id="autoSpinToggle">
      تفعيل دوران العجلة 360 درجة (تلقائي مستمر)
    </label>
    <label class="checkbox-row">
      <input type="checkbox" id="dynamicBreathingToggle" checked>
      تغيير النسب تلقائياً بشكل حيوي (Dynamic Breathing)
    </label>
    <label>
      صورة في منتصف العجلة
      <div class="row">
        <input type="file" id="centerImageInput" accept="image/*">
        <button id="removeImageBtn" type="button">مسح الصورة</button>
      </div>
    </label>
    <label>
      نتيجة آخر دورة
      <span id="spinResult">&mdash;</span>
    </label>
  </div>
  <div id="controls" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-4"></div>
</div>
